## Emacs, make this -*- mode: sh; -*-

FROM ubuntu:24.04

ENV OS_IDENTIFIER ubuntu-2404

# -------------------------------------------------------------------------
# Dependencies
# Install wllvm into the package tree

RUN chmod 0777 /opt

ARG DEBIAN_FRONTEND=noninteractive
ARG LLVM_VERSION=22
ARG RCHK_REPO=https://github.com/kvapca/rchk
ARG RCHK_REF=llvm22
ARG R_SVN_REVISION=HEAD

RUN set -x && \
  sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources

RUN apt-get update && \
  apt-get install -yq --no-install-recommends apt-utils

# Add LLVM package repository
RUN apt-get update && apt-get install -yq ca-certificates wget && \
  wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc >/dev/null && \
  . /etc/os-release && \
  echo "deb http://apt.llvm.org/${VERSION_CODENAME}/ llvm-toolchain-${VERSION_CODENAME}-${LLVM_VERSION} main" > /etc/apt/sources.list.d/llvm.list && \
  echo "deb-src http://apt.llvm.org/${VERSION_CODENAME}/ llvm-toolchain-${VERSION_CODENAME}-${LLVM_VERSION} main" >> /etc/apt/sources.list.d/llvm.list

# Install LLVM
RUN apt-get update && apt-get install -yq \
      clang-${LLVM_VERSION} llvm-${LLVM_VERSION} llvm-${LLVM_VERSION}-dev \
      libllvm${LLVM_VERSION} libc++-${LLVM_VERSION}-dev libc++abi-${LLVM_VERSION}-dev lld-${LLVM_VERSION} make

 
RUN apt-get install -y curl libcurl4-openssl-dev libicu-dev \
             libopenblas-dev libpcre2-dev wget python3-pip \
  && apt-get build-dep -y r-base \
  && apt-get install -y git make clang file \
  && mkdir -p /opt/R/devel-rchk/python \
  && pip3 install --target /opt/R/devel-rchk/python wllvm \
  && for prog in $(ls /opt/R/devel-rchk/python/bin); do \
      sed -i '0,/^import /s//import sys\nsys.path.append("\/opt\/R\/devel-rchk\/python")\n&/' \
          /opt/R/devel-rchk/python/bin/${prog}; \
  done

RUN mkdir -p /opt/R/devel-rchk/bcstore
ENV WLLVM_BC_STORE=/opt/R/devel-rchk/bcstore

# -------------------------------------------------------------------------
# Install rchk into the package tree

ENV WLLVM=/opt/R/devel-rchk/python/bin
ENV RCHK=/opt/R/devel-rchk/rchk
ENV LLVM=/usr/lib/llvm-22

RUN set -x \
    && cd /opt/R/devel-rchk \
    && git clone -b llvm22 --depth 1 https://github.com/kvapca/rchk.git \
    && rm -rf rchk/.git \
    && cd rchk/src \
    && make \
    && cd .. \
    && mkdir -p bin \
    && cp src/*check bin \
    && rm -rf doc examples image src \
    && mv bin src \
    && strip -x src/*

# -------------------------------------------------------------------------
# Packaging tool

RUN curl -LO "https://github.com/goreleaser/nfpm/releases/download/v2.18.1/nfpm_$(dpkg --print-architecture).deb" && \
    apt install -y "./nfpm_$(dpkg --print-architecture).deb" && \
    rm "nfpm_$(dpkg --print-architecture).deb"

# -------------------------------------------------------------------------
# Configure R build

ENV CONFIGURE_OPTIONS="\
    --with-blas=no \
    --with-lapack=no \
    --enable-R-static-lib \
    --with-tcltk \
    --enable-memory-profiling \
    --with-x"

ENV CC=/opt/R/devel-rchk/python/bin/wllvm
ENV CXX="/opt/R/devel-rchk/python/bin/wllvm++ -stdlib=libc++"
ENV CPICFLAGS="-fPIC"
ENV CFLAGS="-Wall -g -O0 -fPIC"
ENV CXXFLAGS="-Wall -g -O0 -fPIC -I/usr/include/libcxxabi"
ENV LLVM_COMPILER=clang
ENV LD="clang++ -stdlib=libc++"

# Override the default pager used by R
ENV PAGER /usr/bin/pager

# R 3.x requires PCRE2 for Pango support on Ubuntu 22
ENV INCLUDE_PCRE2_IN_R_3 yes

COPY builder/rchk.sh /opt/R/devel-rchk/bin/rchk.sh
COPY builder/package.ubuntu-2404-rchk /package.sh
COPY build.sh .
ENTRYPOINT ./build.sh
